spring.application.name=tp-iibdcc-spring-data
# spring.datasource.url=jdbc:h2:mem:products-db
#spring.h2.console.enabled=true
spring.datasource.url=jdbc:mysql://localhost:3306/products_db
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081
